on:
  push:
    branches:
      - repo-sturcture-gha
      - main
    paths:
      - src/**
      - Dockerfile
  # pull_request:
  #     types: [opened, synchronize, reopened]
  workflow_dispatch:

name: image build
env:
  SONAR_HOST_URL:
  REGISTRY_URL:
  APP_NAME:
  REPOSIROTY:
  GIT_CRED_USR:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Short Commit Hash
        run:
          echo "GIT_SHORT_HASH=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
