name: Add contributors
on:
 push:
   branches:
     - master

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: BobAnkh/add-contributors@master
      with:
        CONTRIBUTOR: '@IT-WI-Cloud-Operations/core-team'
        # OR
        CONTRIBUTOR: 'icklpade' 'gheoca01' 'hanab01' # etc...
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        COMMIT_MESSAGE: 'docs(README): update contributors'
        