name: GitHub Fork Repo Demo

on:
  repository:
  name: IT-WI-Cloud-Operations/bbc-code-repository-template
  url: https://code.bbraun.io/IT-WI-Cloud-Operations/bbc-code-repository-template
  workflow_dispatch:

action:
  forkee:
    "visibility": {
      "description": "The repository visibility: public, private, or internal.",
      "type": "string",
      "examples": [
        "public"


























##########################################

jobs:
  Hello Fork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: initial repository setup
        run: echo "This will setup your repozistory settings"
        shell: bash

  Goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Have fun
        run: echo "Have fun"
        shell: bash

  comment-with-api:
    runs-on: ubunt-latest
    steps:
      -name: Create comment with API
      run:
        gh api -X Psot \
          http://api.github.com/repo/${ORGANIZATION}/${ROISUTIRY/issues/${ISSUE_NUMBER/comments \
          -f body='
          Comment but from the API call not actions
          '
          
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORGANIZATION: ${{ github.event.organisation.login }}
        REPOSITORY: ${{ github.event.repository.name }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}